Add default root directory

diff --git a/.github/workflows/droplet-deploy.yml b/.github/workflows/droplet-deploy.yml
--- a/.github/workflows/droplet-deploy.yml
+++ b/.github/workflows/droplet-deploy.yml
@@ -30,6 +30,9 @@ jobs:
       - name: Install SSH client
         run: sudo apt-get install -y openssh-client
 
+      - name: Define ROOT_DIRECTORY
+        run: echo "ROOT_DIRECTORY=${{ github.event.inputs.root_directory || '/root' }}" >> $GITHUB_ENV
+
       - name: Delete existing docker-compose.yml on the server (if exists)
         uses: appleboy/ssh-action@master
         with:
@@ -39,14 +42,15 @@ jobs:
           passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
           port: ${{ secrets.DROPLET_SSH_PORT }}
           script: |
-            if [ -f "${{ github.event.inputs.root_directory }}/.env" ]; then
+            ROOT_DIRECTORY="${{ env.ROOT_DIRECTORY }}" 
+            if [ -f "$ROOT_DIRECTORY/.env" ]; then
               echo "Deleting existing .env file..."
-              rm -f "${{ github.event.inputs.root_directory }}/.env"
+              rm -f "$ROOT_DIRECTORY/.env"
             fi
 
-            if [ -f "${{ github.event.inputs.root_directory }}/docker-compose.yml" ]; then
+            if [ -f "$ROOT_DIRECTORY/docker-compose.yml" ]; then
               echo "Deleting existing docker-compose.yml..."
-              rm -f "${{ github.event.inputs.root_directory }}/docker-compose.yml"
+              rm -f "$ROOT_DIRECTORY/docker-compose.yml"
             fi
 
       - name: Copy docker-compose.yml to the droplet
@@ -58,7 +62,7 @@ jobs:
           passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
           port: ${{ secrets.DROPLET_SSH_PORT }}
           source: ./docker-compose.yml
-          target: ${{ github.event.inputs.root_directory }}
+          target: ${{ env.ROOT_DIRECTORY }}
       
 
       - name: Copy ssl to the droplet
@@ -70,7 +74,7 @@ jobs:
           passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
           port: ${{ secrets.DROPLET_SSH_PORT }}
           source: ./ssl
-          target: ${{ github.event.inputs.root_directory }}
+          target: ${{ env.ROOT_DIRECTORY }}
       
       - name: Copy nginx.conf to the droplet
         uses: appleboy/scp-action@master
@@ -81,7 +85,7 @@ jobs:
           passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
           port: ${{ secrets.DROPLET_SSH_PORT }}
           source: ./nginx.conf
-          target: ${{ github.event.inputs.root_directory }}
+          target: ${{ env.ROOT_DIRECTORY }}
 
       - name: SSH into Droplet, pull image, and run container
         uses: appleboy/ssh-action@master
@@ -92,8 +96,9 @@ jobs:
           port: ${{ secrets.DROPLET_SSH_PORT }}
           passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
           script: |
+            ROOT_DIRECTORY="${{ env.ROOT_DIRECTORY }}"
             # Navigate to the root directory
-            cd ${{ github.event.inputs.root_directory }} || { echo "Error: Directory ${{ github.event.inputs.root_directory }} does not exist"; exit 1; }
+            cd $ROOT_DIRECTORY || { echo "Error: Directory $ROOT_DIRECTORY does not exist"; exit 1; }
 
             # Split input into lines and write to .env file
             echo "Creating .env file..."
@@ -105,7 +110,7 @@ jobs:
 
             # Check if docker-compose.yml exists
             if [ ! -f "docker-compose.yml" ]; then
-              echo "Error: docker-compose.yml not found in directory ${{ github.event.inputs.root_directory }}" >&2
+              echo "Error: docker-compose.yml not found in directory $ROOT_DIRECTORY}" >&2
               exit 1
             fi
             # Pull Database
