Add session notifications (#5)
* Add session type selection

* Add notification preview url

* Add session hash navigation

diff --git a/.github/workflows/restart-containers.yml b/.github/workflows/restart-containers.yml
--- a/.github/workflows/restart-containers.yml
+++ b/.github/workflows/restart-containers.yml
@@ -16,11 +16,14 @@ on:
         default: "no"
 
 jobs:
-  deploy-to-droplet:
+  restart-containers:
     runs-on: ubuntu-latest
     steps:
       - name: Install SSH client
         run: sudo apt-get install -y openssh-client
+
+      - name: Define ROOT_DIRECTORY
+        run: echo "ROOT_DIRECTORY=${{ github.event.inputs.root_directory || '/root' }}" >> $GITHUB_ENV
 
       - name: SSH into Droplet, restart containers
         uses: appleboy/ssh-action@master
@@ -31,24 +34,29 @@ jobs:
           port: ${{ secrets.DROPLET_SSH_PORT }}
           passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
           script: |
+            ROOT_DIRECTORY="${{ env.ROOT_DIRECTORY }}" 
+            RESTART_API="${{ inputs.restart_api }}"
+            RESTART_WEB="${{ inputs.restart_web }}"
             # Navigate to the root directory
-            cd ${{ github.event.inputs.root_directory }} || { echo "Error: Directory ${{ github.event.inputs.root_directory }} does not exist"; exit 1; }
+            cd $ROOT_DIRECTORY || { echo "Error: Directory $ROOT_DIRECTORY does not exist"; exit 1; }
 
             # Check if docker-compose.yml exists
             if [ ! -f "docker-compose.yml" ]; then
-              echo "Error: docker-compose.yml not found in directory ${{ github.event.inputs.root_directory }}" >&2
+              echo "Error: docker-compose.yml not found in directory $ROOT_DIRECTORY" >&2
               exit 1
             fi
-            const restartApi = "${{ inputs.restart_api }}" === "yes";
 
-            if (restartApi) {
+            if [ "$RESTART_API" = "yes" ] && [ "$RESTART_WEB" = "yes" ]; then
+              docker compose up -d
+              exit 0
+            fi
+
+            if [ "$RESTART_API" = "yes" ]; then
               echo "Restarting API..."
-              docker restart quizlo-server || true
-            }
+              docker compose up -d api
+            fi
 
-            const restartWeb = "${{ inputs.restart_web }}" === "yes";
-
-            if (restartWeb) {
+            if [ "$RESTART_WEB" = "yes" ]; then
               echo "Restarting web..."
-              docker restart quizlo-web || true
-            }
+              docker compose up -d web
+            fi
